### ISSUE TITLE
add tags?

### ISSUE THREAD

**Issue by jay8t6** [VACLab/d3-tip#1]
Can you add tags please? so this can be better versioned?

**Comment by davegotz** [comment]
I've been on vacation with limited email access, but I do plan to do this once I  get a chance to sit down at my desk.

Sent from my iPhone

On Aug 17, 2016, at 7:41 PM, jay8t6 <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you add tags please? so this can be better versioned?

##

**Comment by jay8t6** [comment]
Thank you!

**Comment by davegotz** [comment]
Done.  The current version has been tagged "1.0".
