### ISSUE TITLE
Invalid arguments in d3 with ie9

### ISSUE THREAD

**Issue by DBardaji** [VACLab/d3-tip#4]
I detected that when I use your code is working for most of every browser but not for ie9 and it is because a quotation required and it is showing an error in d3 library.

The problem is in the lines 246 and 247. 

in internet explorer 9 needs the quotation around the zeros as well the other properties, so if you change:
      .style('top', 0)
      .style('opacity', 0)
to 
      .style('top', '0')
      .style('opacity', '0')

With this small change this code will work for all browsers since i9 and it will helps with the browser compatibilities

**Comment by davegotz** [comment]
Thanks for reporting this.  I've added this bug fix to the latest version.  

Note that I don't have ie9, so I cannot test the fix.  However, given the trivial nature of the change I'm assuming that the revised version will work right away.  If I'm wrong, please let me know!
